### ISSUE TITLE
count property does not exist

### ISSUE THREAD

**Issue by pasz72** [edvineshagh/New-ScVsProj#1]
New-VsScProj : The property 'count' cannot be found on this object. Verify that the property exists.
At C:\Users\Downloads\New-ScVsProj-master\New-VsScProj.ps1:1631 char:5
-     New-VsScProj -source $source              `
-     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [New-VsScProj], PropertyNotFoundException
  - FullyQualifiedErrorId : PropertyNotFoundStrict,New-VsScProj

**Comment by edvineshagh** [comment]
Thanks for catching the issue pasz.  I pushed the fix back-up to git.
The issue was encountered when specifying Zip file (as appose to Sitecore distribution folder).  

-Edvin
